
const BASE_ENDPOINT="https://the-watcher-comic-backend.herokuapp.com/api/";

const ALLCOMICS_ENDPOINT=BASE_ENDPOINT+"comics";
const STAGECOMIC_ENDPOINT=BASE_ENDPOINT+"stageComic";
const COMICINFO_ENDPOINT=BASE_ENDPOINT+"comicData";


export  {ALLCOMICS_ENDPOINT , COMICINFO_ENDPOINT, STAGECOMIC_ENDPOINT}