const ComicsList =[
    {title:"The Infinity Gaunlet",starRating: "8.4" ,house:"Marvel",year: "1991",genre: "Apocalypse",price:25,salePer:25, newprice: 0,status: true,tag: "SALE",sale:true,image:"https://readcomicsonline.ru/uploads/manga/infinity-gauntlet-19911992/chapters/1/01.jpg"},
    {title:"Old Man Logan",starRating: "2.34" ,house:"Marvel",year: "2008",genre: "Apocalypse",price:53,salePer:75, newprice: 0,status: true,tag: "SALE",sale:true,image:"https://readcomicsonline.ru/uploads/manga/old-man-logan-2015/chapters/1/01.jpg"},
    {title:"Secret Empire ",starRating: "2.34" ,house:"Marvel",year: "2015",genre: "Nazi",price:144,salePer:45, newprice: 0,status: true,tag: "SALE",sale:true,image:"https://readcomicsonline.ru/uploads/manga/secret-empire-2017/chapters/0/01.jpg"},
    {title:"Vision",starRating: "2.34" ,house:"Marvel",year: "2015",genre: "Family",price:113,salePer:50, newprice: 0,status: true,tag: "SALE",sale:true,image:"https://readcomicsonline.ru/uploads/manga/vision-directors-cut-2017/chapters/1/01.jpg"},
    {title:"Civil War II",starRating: "2.34" ,house:"Marvel",year: "2016",genre: "CrossOver",price:100, salePer:0,status:true, tag: "HOT", sale:false,image:"https://readcomicsonline.ru/uploads/manga/civil-war-ii-2016/chapters/1/01.jpg",description:"It's here! The explosive first chapter in the comic event EVERYONE will be talking about. And we come out swinging with a blistering double-sized first issue from the creative team behind last year's best-selling debut of INVINCIBLE IRON MAN and Miles Morales. A new Inhuman, with the ability to profile the future, emerges and the ramifications ripple into every corner of the Marvel Universe. Lines are drawn, bodies fall, and the Marvel Universe will be rocked to it's very core. The action starts here!"},
    {title:"Dark Knight of Steel",starRating: "2.34" ,house:"DC",year: "2021",genre: "Medieval",price:53, salePer:0,status:true, tag: "NEW",sale:false,image:"https://readcomicsonline.ru/uploads/manga/dark-knights-of-steel-2021/chapters/1/01.jpg"},
    {title:"Devil’s reign ",starRating: "2.34" ,house:"Marvel",year: "2021",genre: "Politics",price:144, salePer:0,status:true, tag: "NEW",sale:false,image:"https://readcomicsonline.ru/uploads/manga/devils-reign-2021/chapters/1/01.jpg"},
    {title:"Batman: The killing joke",starRating: "2.34" ,house:"DC",year: "1988",genre: "Gore",price:113, salePer:0,status:false, tag: "null",sale:false,image:"https://readcomicsonline.ru/uploads/manga/batman-the-killing-joke/chapters/the-killing-joke/01.jpg"},
    {title:"Flashpoint Beyond",starRating: "4.34" ,house:"DC",year: "2022",genre: "Timetravel",price:100, salePer:0,status:true, tag: "HOT",sale:false,image:"https://readcomicsonline.ru/uploads/manga/flashpoint-beyond-2022/chapters/1/01.jpg", description:"After sacrificing everything to help The Flash put the universe back together and save Bruce Wayne’s life, Thomas Wayne wakes up in a world he thought was no more. Forced to don the cowl once again, Batman prowls the streets of Gotham City searching for answers to how this world still exists, but what he starts to uncover will send him hurtling around the globe. The hunt for the Clockwork Killer starts here!"},
    {title:"Eternals",starRating: "5.00" ,house:"Marvel",year: "2021",genre: "Mythology",price:75, salePer:0,status:true, tag: "HOT",sale:false,image:"https://readcomicsonline.ru/uploads/manga/eternals-2021/chapters/1/01.jpg", description:"NEVER DIE. NEVER WIN. ETERNALS. What's the point of an eternal battle? For millions of years, one hundred Eternals have roamed the Earth, secret protectors of humanity. Without them, we'd be smears between the teeth of the demon-like Deviants. Their war has waged for all time, echoing in our myths and nightmares. But today, Eternals face something new: change. Can they – or anyone on Earth – survive their discovery? From the thought provoking minds of Kieron Gillen (The Wicked + The Divine, Uncanny X-Men, Thor) and Esad Ribić (Secret Wars, King Thor) comes a new vision of the classic Marvel mythology!"},
  ];
export default ComicsList